services:
  PostgresTest:
    build: .
    image: testpostgre.0.1.0
    container_name: mypostgretest_container
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/testpostgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=root

  #happy_db:
   # image: postgres:14-alpine
   # container_name: happy_db_container
   # ports:
   #   - "6541:5432"
   # environment:
   #   - POSTGRES_DB=happy_db
   #   - POSTGRES_USER=happy_day
   #   - POSTGRES_PASSWORD=root
